main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.desktop_view, name='desktop'),
]

polos/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('shop/', include('shop.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('minesweeper/', include('minesweeper.urls')),
    path('paint/', include('paint.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/views.py
from django.shortcuts import render

def desktop_view(request):
    # Использование сессий Django
    if 'visit_count' not in request.session:
        request.session['visit_count'] = 0
    request.session['visit_count'] += 1
    
    # Сохраняем информацию о последнем посещении
    request.session['last_visit'] = str(request.session.get('visit_count'))
    
    context = {
        'visit_count': request.session['visit_count'],
        'last_visit': request.session.get('last_visit'),
    }
    
    return render(request, 'main/index/index.html', context)

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="csrf-token" content="{{ csrf_token }}">
  <title>{% block title %}Polos - Retro Futurism{% endblock %}</title>
  <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
  {% block extra_css %}{% endblock %}
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <div class="taskbar">
    <div id="startButton" class="start-button">Пуск</div>
    <div class="taskbar-right">
      <div id="clock-taskbar"></div>
    </div>
  </div>


  <div id="startMenu" class="start-menu">
    <ul>
      <li><a href="{% url 'main:desktop' %}
">На рабочий стол</a></li>  
    </ul>
  </div>

  <script src="{% static 'js/clock.js' %}"></script>  
  <script src="{% static 'js/startmenu.js' %}"></script>  
  {% block extra_js %}{% endblock %}
</body>
</html>